language: r
cache: packages
latex: false
fortran: false
pandoc: false
r_check_args: '--run-donttest'

matrix:
  include:
    - r: 3.5
    - dist: trusty
    - dist: xenial
    - dist: xenial
      addons:
        apt:
          update: true
          packages: libavfilter-dev
          sources:
            - sourceline: 'ppa:cran/ffmpeg-4'
            - sourceline: 'ppa:cran/ffmpeg-3'
    - r: devel
    - os: osx
      brew_packages: ffmpeg
    - os: osx
      osx_image: xcode11.4
      disable_homebrew: true
    - os: osx
      disable_homebrew: true
      osx_image: xcode10.1
    - r: 3.6.3
      os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    update: true
    packages: libavdevice-dev
    sources:
      - sourceline: 'ppa:cran/ffmpeg-3'
